Repository Strawberry-Team/calendula-backend, pull requests merged in 2025-03, with the labels that each got.

#4 Add database migration setup
  .db-migraterc
  .gitignore
  README.md
  db/migration_config.json.example
  db/migrations/20250311164251-db-init.js
  db/migrations/package.json
  db/migrations/sqls/20250311164251-db-init-down.sql
  db/migrations/sqls/20250311164251-db-init-up.sql
  db/schema.sql
  package-lock.json
  package.json
  playwright.config.js
Labels: enhancement

#3 Add support for managing calendar participants
  docs/openapi.json
  src/calendar/controller.js
  src/calendar/entity.js
  src/calendar/model.js
  src/calendar/user/entity.js
  src/calendar/user/model.js
  src/controller.js
  src/user/entity.js
  tests/api/calendars.test.js
  tests/api/helpers/calendars.helpers.js
Labels: documentation, enhancement

#5 Refactor Playwright tests, add fake data for tests
  package-lock.json
  package.json
  playwright.config.js
  tests/api/auth.test.js
  tests/api/calendars.test.js
  tests/api/events.test.js
  tests/api/helpers/calendars.helpers.js
  tests/api/helpers/events.helpers.js
  tests/api/helpers/general.helpers.js
  tests/api/helpers/users.helpers.js
Labels: enhancement

#6 Add join/leave calendar functionality and auto-create main calendar
  docs/openapi.json
  src/auth/controller.js
  src/calendar/controller.js
  src/calendar/model.js
  src/calendar/routes.js
  src/calendar/user/model.js
  src/db.js
Labels: enhancement

#12 Refactor token creation methods in auth and user controllers
  src/auth/controller.js
  src/user/controller.js
  src/user/model.js
Labels: invalid

#26 Update generation of dates in fake data
  tests/api/helpers/events.helpers.js
  tests/fake-data/fake-data.test.js
  tests/fake-data/helpers/fake.events.helpers.js
Labels: invalid

#27 Fix email sending issue & update email templates
  mailer/calendarInvitation.html
  mailer/eventInvitation.html
  mailer/service.js
  package.json
  src/calendar/controller.js
  src/event/controller.js
Labels: bug

#35 Enable toggle for database query logging via env variable
  .env.development.example
  .env.test.example
  src/db.js
Labels: enhancement
